# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# /////////////////////////////////////////////
# // FORMAT
# /////////////////////////////////////////////

format = """
[╭](color_bg)\
$os\
[](bg:color_bg fg:color_fg)\
$directory\
$git_branch\
$git_status\
[](color_bg)\
$fill\
[](color_bg)\
$username\
$sudo\
$line_break\
[╰](color_bg)\
$character
"""

# /////////////////////////////////////////////
# // COLORS
# /////////////////////////////////////////////

palette = 'nordtheme'

[palettes.nordtheme]
color_fg = '#d8dee9'
color_bg = '#2e3440'
color_red = '#bf616a'
color_green = '#a3be8c'
color_purple = '#b48ead'
color_yellow = '#ebcb8b'
color_orange = '#d08770'
color_white1 = '#d8dee9'
color_white2 = '#e5e9f0'
color_white3 = '#eceff4'
color_black1 = '#2e3440'
color_black2 = '#3b4252'
color_black3 = '#434c5e'
color_black4 = '#4c566a'
color_blue1 = '#5e81ac'
color_blue2 = '#81a1c1'
color_blue3 = '#88c0d0'
color_blue4 = '#8fbcbb'

# /////////////////////////////////////////////
# // MODULES
# /////////////////////////////////////////////

[os]
disabled = false
style = "bg:color_bg fg:color_fg"
format = "[$symbol]($style)"

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[directory]
style = "bg:color_bg fg:color_fg"
home_symbol = "~"
read_only = " "
read_only_style = "bg:color_bg fg:color_red"
format = "[  ](bg:color_bg fg:color_blue1)[ $path]($style)[$read_only ]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
symbol = ""
style = "bg:color_bg fg:color_green"
format = "[](bg:color_bg fg:color_fg)[ $symbol $branch ]($style)"

[git_status]
style = "bg:color_bg fg:color_orange"
format = "[$all_status$ahead_behind ]($style)"

[fill]
symbol = "─"
style = "fg:color_bg"

[username]
disabled = false
show_always = true
style_user = "bg:color_bg fg:color_blue1"
style_root = "bg:color_red fg:color_red"
format = "[  ]($style)[$user ](bg:color_bg fg:color_fg)"

[sudo]
disabled = false
symbol = '󰌆 ' 
style = "bg:color_bg fg:color_red"
format = "[$symbol ]($style)"

[line_break]
disabled = false

[character]
disabled = false
error_symbol = "[⮞](bold fg:color_red)"
success_symbol = "[⮞](bold fg:color_green)"